apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
  labels:
    app: employee-api
spec:
  selector:
    app: employee-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
