apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: your-dockerhub/employee-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: employee-api-config
