apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: employee-api.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: employee-api-service
                port:
                  number: 80
